/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traslate;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author sofia
 */
public class Traductor extends javax.swing.JFrame {

    /**
     * Creates new form Traductor
     */
    public Traductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ingresaPalabra = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonEspIn = new javax.swing.JButton();
        buttonInEsp = new javax.swing.JButton();
        buttonEspFr = new javax.swing.JButton();
        buttonFrEsp = new javax.swing.JButton();
        buttonEspAl = new javax.swing.JButton();
        buttonAlEsp = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        campoTraduccion = new javax.swing.JTextField();
        campoPalabra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRADUCTOR");
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, -1));

        ingresaPalabra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ingresaPalabra.setText("Ingresa tu palabra: ");
        Bg.add(ingresaPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 132, 28));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        buttonEspIn.setBackground(new java.awt.Color(204, 204, 255));
        buttonEspIn.setText("Español ---> Ingles");
        buttonEspIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspInActionPerformed(evt);
            }
        });

        buttonInEsp.setBackground(new java.awt.Color(204, 204, 255));
        buttonInEsp.setText("Ingles ---> Español");
        buttonInEsp.setBorderPainted(false);
        buttonInEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInEspActionPerformed(evt);
            }
        });

        buttonEspFr.setBackground(new java.awt.Color(204, 204, 255));
        buttonEspFr.setText("Español ---> Frances");
        buttonEspFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspFrActionPerformed(evt);
            }
        });

        buttonFrEsp.setBackground(new java.awt.Color(204, 204, 255));
        buttonFrEsp.setText("Frances ---> Español");
        buttonFrEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFrEspActionPerformed(evt);
            }
        });

        buttonEspAl.setBackground(new java.awt.Color(204, 204, 255));
        buttonEspAl.setText("Español ---> Aleman");
        buttonEspAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspAlActionPerformed(evt);
            }
        });

        buttonAlEsp.setBackground(new java.awt.Color(204, 204, 255));
        buttonAlEsp.setText("Aleman ---> Español");
        buttonAlEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlEspActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEspIn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEspFr, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFrEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEspAl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAlEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonEspIn)
                .addGap(18, 18, 18)
                .addComponent(buttonInEsp)
                .addGap(18, 18, 18)
                .addComponent(buttonEspFr)
                .addGap(18, 18, 18)
                .addComponent(buttonFrEsp)
                .addGap(18, 18, 18)
                .addComponent(buttonEspAl)
                .addGap(18, 18, 18)
                .addComponent(buttonAlEsp)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 300));

        resultado.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        Bg.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 226, 220, 50));
        Bg.add(campoTraduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 290, 297));

        campoPalabra.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        campoPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPalabraActionPerformed(evt);
            }
        });
        Bg.add(campoPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 290, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPalabraActionPerformed
        String entrada = campoPalabra.getText();
        if(entrada.length() <= 0){
            JOptionPane.showMessageDialog(null, "No has ingresado nada para traducir");
            return;
        }
    }//GEN-LAST:event_campoPalabraActionPerformed

    private void buttonEspInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspInActionPerformed
      
        
         HashMap<String, String> ingles = new HashMap<>();
       
       ingles.put("libro","book");
       ingles.put("gato","cat");
       ingles.put("gente","people");
       ingles.put("extranjero","abroad");
       ingles.put("adulto","adult");
       ingles.put("oso","bear");
       ingles.put("valiente","brave");
       ingles.put("breve","brief");
       ingles.put("calma","calm");
       ingles.put("accidente","accident");
       ingles.put("actor","actor");
       ingles.put("asunto","affair");
       ingles.put("acuerdo","agreement");
       ingles.put("airport","aeropuerto");
       ingles.put("ambicion","ambition");
       ingles.put("analista","analyst");
       ingles.put("abuso","abuse");
       ingles.put("activo","active");
       ingles.put("avance","advance");
       ingles.put("alternativa","alternative");
       ingles.put("anuario","annual");
       ingles.put("ceniza","ash");
       ingles.put("edad","age");
       ingles.put("aire","air");
       ingles.put("animal","animal");
       ingles.put("respuesta","answer");
       ingles.put("manzana","apple");
       ingles.put("arte","art");
       ingles.put("bebe","baby");
       ingles.put("agrupacion","combine");
       ingles.put("choque","clash");
       ingles.put("mencion","mention");
       ingles.put("mina","mine");
       ingles.put("señorita","miss");
       ingles.put("nadie","nobody");
       ingles.put("ordinario","ordinary");
       ingles.put("permiso","permit");
       ingles.put("gaseosa","pop");
       ingles.put("choque","crash");
       ingles.put("reto","dare");
       ingles.put("retraso","delay");
       ingles.put("dependiente","dependent");
       ingles.put("excavasion","dig");
       ingles.put("division","divide");
       ingles.put("duda","doubt");
       ingles.put("equivalente","equivalent");
       ingles.put("fuga","escape");
       ingles.put("hembra","famale");
       ingles.put("doblez","fold");
       ingles.put("eternidad","forever");
        ingles.put("aviso","prompt");
       ingles.put("puñetazo","punch");
       ingles.put("tranquilidad","quiet");
       ingles.put("cita","quote");
       ingles.put("desecho","refuse");
       ingles.put("remordimiento","regret");
       ingles.put("reparacion","repair");
       ingles.put("repeticion","repeat");
       ingles.put("replica","reply");
       ingles.put("rollo","roll");
       ingles.put("odio","hate");
       ingles.put("caza","hunt");
       ingles.put("apuro","hurry");
       ingles.put("invitacion","invite");
       ingles.put("beso","kiss");
       ingles.put("risa","laugh");
       ingles.put("macho","male");
       ingles.put("marcha","march");
       ingles.put("ronda","rough");
       ingles.put("realeza","royal");
       ingles.put("prisa","rush");
       ingles.put("rasguño","scratch");
       ingles.put("mayor","senior");
       ingles.put("sacudida","shake");
       ingles.put("shift","cambio");
       ingles.put("brillo","shine");
       ingles.put("resbalon","slip");
       ingles.put("olor","smell");
       ingles.put("sonrisa","smile");
       ingles.put("repuesto","spare");
       ingles.put("hechizo","spell");
       ingles.put("espiritual","spiritual");
       ingles.put("separacion","split");
       ingles.put("tension","strain");
       ingles.put("tramo","stretch");
       ingles.put("huelga","strike");
       ingles.put("tira","strip");
       ingles.put("lucha","struggle");
       ingles.put("lagrima","tear");
       ingles.put("corbata","tie");
       ingles.put("tren","train");
       ingles.put("giro","twist");
       ingles.put("usual","usual");
       ingles.put("velorio","wake");
       ingles.put("lavado","wash");
       ingles.put("deseo","wish");
       ingles.put("amarillo","yellow");
       ingles.put("ayer","yesterday");
       ingles.put("enfermo","sick");
       ingles.put("tonto","silly");
       
       String palabra = campoPalabra.getText();
       
       String traduccion = ingles.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(ingles.containsKey(palabra)){
           
            resultado.setText(traduccion);
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
        
    }//GEN-LAST:event_buttonEspInActionPerformed

    private void buttonInEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInEspActionPerformed
       HashMap<String, String> ingles = new HashMap<>();
       
       ingles.put("book","libro");
       ingles.put("cat","gato");
       ingles.put("people","gente");
       ingles.put("abroad","extranjero");
       ingles.put("adult","adulto");
       ingles.put("bear","oso");
       ingles.put("brave","valiente");
       ingles.put("brief","breve");
       ingles.put("calm","calma");
       ingles.put("accident","accidente");
       ingles.put("actor","actor");
       ingles.put("affair","asunto");
       ingles.put("agreement","acuerdo");
       ingles.put("airport","aeropuerto");
       ingles.put("ambition","ambicion");
       ingles.put("analyst","analista");
       ingles.put("abuse","abuso");
       ingles.put("active","activo");
       ingles.put("advance","avance");
       ingles.put("alternative","alternativa");
       ingles.put("annual","anuario");
       ingles.put("ash","ceniza");
       ingles.put("age","edad");
       ingles.put("air","aire");
       ingles.put("animal","animal");
       ingles.put("answer","respuesta");
       ingles.put("apple","manzana");
       ingles.put("art","arte");
       ingles.put("baby","bebe");
       ingles.put("combine","agrupacion");
       ingles.put("clash","choque");
       ingles.put("mention","mencion");
       ingles.put("mine","mina");
       ingles.put("miss","señorita");
       ingles.put("nobody","nadie");
       ingles.put("ordinary","ordinario");
       ingles.put("permit","permiso");
       ingles.put("pop","gaseosa");
       ingles.put("crash","choque");
       ingles.put("dare","reto");
       ingles.put("delay","retraso");
       ingles.put("dependent","dependiente");
       ingles.put("dig","excavasion");
       ingles.put("divide","division");
       ingles.put("doubt","duda");
       ingles.put("equivalent","equivalente");
       ingles.put("escape","fuga");
       ingles.put("famale","hembra");
       ingles.put("fold","doblez");
       ingles.put("forever","eternidad");
        ingles.put("prompt","aviso");
       ingles.put("punch","puñetazo");
       ingles.put("quiet","tranquilidad");
       ingles.put("quote","cita");
       ingles.put("refuse","desecho");
       ingles.put("regret","remordimiento");
       ingles.put("repair","reparacion");
       ingles.put("repeat","repeticion");
       ingles.put("reply","replica");
       ingles.put("roll","rollo");
       ingles.put("hate","odio");
       ingles.put("hunt","caza");
       ingles.put("hurry","apuro");
       ingles.put("invite","invitacion");
       ingles.put("kiss","beso");
       ingles.put("laugh","risa");
       ingles.put("male","macho");
       ingles.put("march","marcha");
       ingles.put("rough","ronda");
       ingles.put("royal","realeza");
       ingles.put("rush","prisa");
       ingles.put("scratch","rasguño");
       ingles.put("senior","mayor");
       ingles.put("shake","sacudida");
       ingles.put("shift","cambio");
       ingles.put("shine","brillo");
       ingles.put("slip","resbalon");
       ingles.put("smell","olor");
       ingles.put("smile","sonrisa");
       ingles.put("spare","repuesto");
       ingles.put("spell","hechizo");
       ingles.put("spiritual","espiritual");
       ingles.put("split","separacion");
       ingles.put("strain","tension");
       ingles.put("stretch","tramo");
       ingles.put("strike","huelga");
       ingles.put("strip","tira");
       ingles.put("struggle","lucha");
       ingles.put("tear","lagrima");
       ingles.put("tie","corbata");
       ingles.put("train","tren");
       ingles.put("twist","giro");
       ingles.put("usual","usual");
       ingles.put("wake","velorio");
       ingles.put("wash","lavado");
       ingles.put("wish","deseo");
       ingles.put("yellow","amarillo");
       ingles.put("yesterday","ayer");
       ingles.put("sick","enfermo");
       ingles.put("silly","tonto");
       
       String palabra = campoPalabra.getText();
       
       String traduccion = ingles.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(ingles.containsKey(palabra)){
           
            resultado.setText(traduccion);
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
       
       
       
        
    }//GEN-LAST:event_buttonInEspActionPerformed

    private void buttonEspFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspFrActionPerformed
       
       HashMap<String, String> frances = new HashMap<>();
       
       frances.put("casa","maison");
       frances.put("ciudad","ville");
       frances.put("puerta","porte");
       frances.put("ruta","route");
       frances.put("hombre","homme");
       frances.put("mujer","femme");
       frances.put("amor","amour");
       frances.put("carro","voiture");
       frances.put("bien","bien");
       frances.put("tiempo","temps");
       frances.put("veces","fois");
       frances.put("calle","rue");
       frances.put("mundo","monde");
       frances.put("pais","pays");
       frances.put("razon","raison");
       frances.put("dios","dieu");
       frances.put("dia","jour");
       frances.put("señor","monsieur");
       frances.put("persona","personne");
       frances.put("parte","part");
       frances.put("cuarto","chambre");
       frances.put("señora","madame");
       frances.put("gracias","merci");
       frances.put("si","oui");
       frances.put("no","non");
       frances.put("comida","nourriture");
       frances.put("bebida","boisson");
       frances.put("agua","eau");
       frances.put("frutas","fruits");
       frances.put("verduras","legumes");
       frances.put("pan","pain");
       frances.put("vino","vin");
       frances.put("queso","fromage");
       frances.put("carne","viande");
       frances.put("ensalada","salade");
       frances.put("viajes","voyages");
       frances.put("pasaporte","passeport");
       frances.put("avion","avion");
       frances.put("aeropuerto","aeroport");
       frances.put("autobus","bus");
       frances.put("equipaje","bagages");
       frances.put("cuarto","chambre");
       frances.put("cama","lit");
       frances.put("baño","salle de bain");
       frances.put("retrete","toilettes");
       frances.put("cocina","cuisine");
       frances.put("comedor","salle a manger");
       frances.put("mesa","table");
       frances.put("sala","salon");
       frances.put("familia","famille");
       frances.put("esposo","mari");
       frances.put("pére","padre");
       frances.put("mere","madre");
       frances.put("hijo","fils");
       frances.put("hija","fille");
       frances.put("amigo","ami");
       frances.put("amiga","amie");
       frances.put("hola","bonjour");
       frances.put("cartera","portefeuille");
       frances.put("joyas","bijoux");
       frances.put("mechero","briquet");
       frances.put("martillo","marteau");
       frances.put("boligrafo","stylo");
       frances.put("cajon","tiroir");
       frances.put("factura","facture");
       frances.put("paquete","paquet");
       frances.put("pañuelo","mouchoir");
       frances.put("clip","trombone");
       frances.put("bolsillo","poche");
       frances.put("nueces","noix");
       frances.put("cuerda","corde");
       frances.put("tostadora","grille pain");
       frances.put("impresora","imprimante");
       frances.put("desodorante","deodorant");
       frances.put("caja","caisse");
       frances.put("madera","bois");
       frances.put("revista","magazine");
       frances.put("tinta","couleur");
       frances.put("pesas","poids");
       frances.put("boleto","ticket");
       frances.put("ascensor","ascenseur");
       frances.put("horno","four");
       frances.put("corbata","cravate");
       frances.put("aguja","aiguille");
       frances.put("anillo","bague");
       frances.put("pasto","herbe");
       frances.put("foco","ampoule");
       frances.put("cortina","rideau");
       frances.put("escalera","escalier");
       frances.put("teclado","clavier");
       frances.put("pantalla","ecran");
       frances.put("rueda","roue");
       frances.put("paraguas","parapluie");
       frances.put("candado","cadenas");
       frances.put("tuberia","tuyauterie");
       frances.put("hueso","os");
       frances.put("ladrillo","brique");
       frances.put("collar"," collier");
       frances.put("espejo","miroir");
       
       
       String palabra = campoPalabra.getText();
       
       String traduccion = frances.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(frances.containsKey(palabra)){
           
            resultado.setText(traduccion);
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
       
        
    }//GEN-LAST:event_buttonEspFrActionPerformed

    private void buttonFrEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFrEspActionPerformed
        HashMap<String, String> frances = new HashMap<>();
       
       frances.put("maison","casa");
       frances.put("ville","ciudad");
       frances.put("porte","puerta");
       frances.put("route","ruta");
       frances.put("homme","hombre");
       frances.put("femme","mujer");
       frances.put("amour","amor");
       frances.put("voiture","carro");
       frances.put("bien","bien");
       frances.put("temps","tiempo");
       frances.put("fois","veces");
       frances.put("rue","calle");
       frances.put("monde","mundo");
       frances.put("pays","pais");
       frances.put("raison","razon");
       frances.put("dieu","dios");
       frances.put("jour","dia");
       frances.put("monsieur","señor");
       frances.put("personne","persona");
       frances.put("part","parte");
       frances.put("chambre","cuarto");
       frances.put("madame","señora");
       frances.put("merci","gracias");
       frances.put("oui","si");
       frances.put("non","no");
       frances.put("nourriture","comida");
       frances.put("boisson","bebida");
       frances.put("eau","agua");
       frances.put("fruits","frutas");
       frances.put("legumes","verduras");
       frances.put("pain","pan");
       frances.put("vin","vino");
       frances.put("fromage","queso");
       frances.put("viande","carne");
       frances.put("salade","ensalada");
       frances.put("voyages","viajes");
       frances.put("passeport","pasaporte");
       frances.put("avion","avion");
       frances.put("aeropuerto","aeroport");
       frances.put("bus","autobus");
       frances.put("bagages","equipaje");
       frances.put("chambre","cuarto");
       frances.put("lit","cama");
       frances.put("salle de bain","baño");
       frances.put("toilettes","retrete");
       frances.put("cuisine","cocina");
       frances.put("salle a manger","comedor");
       frances.put("table","mesa");
       frances.put("salon","sala");
       frances.put("famille","familia");
       frances.put("mari","esposo");
       frances.put("padre","pére");
       frances.put("madre","mere");
       frances.put("fils","hijo");
       frances.put("fille","hija");
       frances.put("ami","amigo");
       frances.put("amie","amiga");
       frances.put("bonjour","hola");
       frances.put("portefeuille","cartera");
       frances.put("bijoux","joyas");
       frances.put("briquet","mechero");
       frances.put("marteau","martillo");
       frances.put("stylo","boligrafo");
       frances.put("tiroir","cajon");
       frances.put("facture","factura");
       frances.put("paquet","paquete");
       frances.put("mouchoir","pañuelo");
       frances.put("trombone","clip");
       frances.put("poche","bolsillo");
       frances.put("noix","nueces");
       frances.put("corde","cuerda");
       frances.put("grille pain","tostadora");
       frances.put("imprimante","impresora");
       frances.put("deodorant","desodorante");
       frances.put("caisse","caja");
       frances.put("bois","madera");
       frances.put("magazine","revista");
       frances.put("couleur","tinta");
       frances.put("poids","pesas");
       frances.put("ticket","boleto");
       frances.put("ascenseur","ascensor");
       frances.put("four","horno");
       frances.put("cravate","corbata");
       frances.put("aiguille","aguja");
       frances.put("bague","anillo");
       frances.put("herbe","pasto");
       frances.put("ampoule","foco");
       frances.put("rideau","cortina");
       frances.put("escalier","escalera");
       frances.put("clavier","teclado");
       frances.put("ecran","pantalla");
       frances.put("roue","rueda");
       frances.put("parapluie","paraguas");
       frances.put("cadenas","candado");
       frances.put("tuyauterie","tuberia");
       frances.put("os","hueso");
       frances.put("brique","ladrillo");
       frances.put("collier","collar");
       frances.put("miroir","espejo");
       
       
       String palabra = campoPalabra.getText();
       
       String traduccion = frances.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(frances.containsKey(palabra)){
           
           resultado.setText(traduccion); 
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
        
    }//GEN-LAST:event_buttonFrEspActionPerformed

    private void buttonEspAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspAlActionPerformed
      
      HashMap<String, String> aleman= new HashMap<>();
      
      aleman.put("el", "der");
      aleman.put("la", "die");
      aleman.put("y", "und");
      aleman.put("in", "en");
      aleman.put("de", "von");
      aleman.put("a", "zu");
      aleman.put("mit", "con");
      aleman.put("para", "für");
      aleman.put("es", "ist");
      aleman.put("este", "diesem");
      
      aleman.put("desde", "seit");
      aleman.put("todos", "alle");
      aleman.put("pero", "doch");
      aleman.put("ahora", "jetzt");
      aleman.put("fueron", "waren");
      aleman.put("tres", "drei");
      aleman.put("años", "jahre");
      aleman.put("nuevo", "neue");
      aleman.put("ya", "bereits");
      aleman.put("porque", "da");
      
      aleman.put("tambien", "auch");
      aleman.put("primero", "ersten");
      aleman.put("hacia", "nach");
      aleman.put("sin", "ohne");
      aleman.put("pero", "sondern");
      aleman.put("ahora", "nun");
      aleman.put("aproximadamente", "etwa");
      aleman.put("en", "bei");
      aleman.put("hoy", "heute");
      aleman.put("Alemania", "Deutschland");
      
      aleman.put("otro", "anderen");
      aleman.put("final", "ende");
      aleman.put("tiempo", "zeit");
      aleman.put("ciudad", "stadt");
      aleman.put("solamente", "erst");
      aleman.put("Berlin", "Berlin");
      aleman.put("hacer", "machen");
      aleman.put("dejar", "lassen");
      aleman.put("empresa", "unternehmen");
      aleman.put("aunque", "allerdings");
      
      aleman.put("cuatro", "vier");
      aleman.put("bueno", "gut");
      aleman.put("muchos", "viele");
      aleman.put("casi", "fast");
      aleman.put("cinco", "fünf");
      aleman.put("hombre", "mann");
      aleman.put("vida", "leben");
      aleman.put("mundo", "welt");
      aleman.put("gobierno", "regierung");
      aleman.put("mujeres", "frauen");
      
      aleman.put("pais", "land");
      aleman.put("diez", "zehn");
      aleman.put("si", "ja");
      aleman.put("niños", "kinder");
      aleman.put("pregunta", "frage");
      aleman.put("ayer", "gestern");
      aleman.put("parte", "teil");
      aleman.put("policia", "polizei");
      aleman.put("justo", "gerade");
      aleman.put("dinero", "geld");
      
      aleman.put("caida", "fall");
      aleman.put("ir", "gehen");
      aleman.put("vez", "mal");
      aleman.put("camino", "weg");
      aleman.put("seis", "sechs");
      aleman.put("semana", "woche");
      aleman.put("contra", "dagegen");
      aleman.put("viejo", "alt");
      aleman.put("dia", "tag");
      aleman.put("especie", "art");
      
      aleman.put("recibir", "erhalten");
      aleman.put("uno", "man");
      aleman.put("cada", "jeder");
      aleman.put("nunca", "nie");
      aleman.put("quedarse", "bleiben");
      aleman.put("año", "jahres");
      aleman.put("solo", "allein");
      aleman.put("claramente", "deutlich");
      aleman.put("desarrollo", "entwicklung");
      aleman.put("presidente", "präsident");
      
      aleman.put("lugar", "platz");
      aleman.put("lunes", "montag");
      aleman.put("domingo", "sonntag");
      aleman.put("simplemente", "einfach");
      aleman.put("antes", "eher");
      aleman.put("numero", "zahl");
      aleman.put("siguiente", "neben");
      aleman.put("lejos", "weit");
      aleman.put("partido", "partei");
      aleman.put("tema", "thema");
      
      aleman.put("politica", "politik");
      aleman.put("segundo", "zweiten");
      aleman.put("enero", "januar");
      aleman.put("total", "inesgesamt");
      aleman.put("siempre", "je");
      aleman.put("mucho", "vielen");
      aleman.put("necesario", "darf");
      aleman.put("nombres", "namen");
      aleman.put("casa", "haus");
      aleman.put("ayuda", "hilfe");
      
      String palabra = campoPalabra.getText();
       
       String traduccion = aleman.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(aleman.containsKey(palabra)){
           
            resultado.setText(traduccion);
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
        
        
    }//GEN-LAST:event_buttonEspAlActionPerformed

    private void buttonAlEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlEspActionPerformed
      
          HashMap<String, String> aleman= new HashMap<>();
      
      aleman.put( "der","el");
      aleman.put("die", "la");
      aleman.put( "und","y");
      aleman.put( "en","in");
      aleman.put( "von","de");
      aleman.put( "zu","a");
      aleman.put( "con","mit");
      aleman.put( "für","para");
      aleman.put( "ist","es");
      aleman.put("diesem", "este");
      
      aleman.put( "seit","desde");
      aleman.put( "alle","todos");
      aleman.put( "doch","pero");
      aleman.put( "jetzt","ahora");
      aleman.put( "waren","fueron");
      aleman.put( "drei","tres");
      aleman.put( "jahre","años");
      aleman.put( "neue","nuevo");
      aleman.put( "bereits","ya");
      aleman.put( "da","porque");
      
      aleman.put("auch", "tambien");
      aleman.put( "ersten","primero");
      aleman.put( "nach","hacia");
      aleman.put( "ohne","sin");
      aleman.put("sondern", "pero");
      aleman.put( "nun","ahora");
      aleman.put( "etwa","aproximadamente");
      aleman.put( "bei","en");
      aleman.put("heute", "hoy");
      aleman.put( "Deutschland","Alemania");
      
      aleman.put("anderen", "otro");
      aleman.put( "ende","final");
      aleman.put( "zeit","tiempo");
      aleman.put("stadt", "ciudad");
      aleman.put("erst","solamente" );
      aleman.put("Berlin", "Berlin");
      aleman.put( "machen","hacer");
      aleman.put("lassen", "dejar");
      aleman.put("unternehmen", "empresa");
      aleman.put("allerdings", "aunque");
      
      aleman.put("vier", "cuatro");
      aleman.put("gut", "bueno");
      aleman.put("viele","muchos" );
      aleman.put( "fast","casi");
      aleman.put( "fünf","cinco");
      aleman.put( "mann","hombre");
      aleman.put("leben","vida" );
      aleman.put("welt", "mundo");
      aleman.put( "regierung","gobierno");
      aleman.put( "frauen","mujeres");
      
      aleman.put("land","pais" );
      aleman.put("zehn","diez" );
      aleman.put("ja", "si");
      aleman.put("kinder","niños" );
      aleman.put("frage","pregunta" );
      aleman.put("gestern","ayer" );
      aleman.put("teil","parte" );
      aleman.put( "polizei","policia");
      aleman.put("gerade","justo" );
      aleman.put( "geld","dinero");
      
      aleman.put("fall","caida" );
      aleman.put("gehen","ir" );
      aleman.put("mal","vez" );
      aleman.put("weg","camino" );
      aleman.put("sechs","seis" );
      aleman.put("woche","semana" );
      aleman.put("dagegen","contra" );
      aleman.put("alt","viejo" );
      aleman.put("tag","dia" );
      aleman.put("art","especie" );
      
      aleman.put("erhalten","recibir" );
      aleman.put("man","uno" );
      aleman.put("jeder","cada" );
      aleman.put("nie","nunca" );
      aleman.put("bleiben","quedarse" );
      aleman.put("jahres","año" );
      aleman.put("allein","solo" );
      aleman.put("deutlich","claramente" );
      aleman.put("entwicklung","desarrollo" );
      aleman.put("präsident","presidente" );
      
      aleman.put( "platz","lugar");
      aleman.put( "montag","lunes");
      aleman.put("sonntag","domingo" );
      aleman.put("einfach","simplemente" );
      aleman.put("eher","antes" );
      aleman.put("zahl","numero" );
      aleman.put("neben","siguiente");
      aleman.put("weit","lejos" );
      aleman.put("partei","partido" );
      aleman.put("thema","tema" );
      
      aleman.put("politik","politica" );
      aleman.put("zweiten","segundo" );
      aleman.put("januar","enero" );
      aleman.put("inesgesamt","total" );
      aleman.put( "je","siempre");
      aleman.put("vielen","mucho" );
      aleman.put("darf","necesario" );
      aleman.put("namen","nombres" );
      aleman.put("haus","casa" );
      aleman.put("hilfe","ayuda" );
      
      String palabra = campoPalabra.getText();
       
       String traduccion = aleman.get(palabra);
       
       String aviso ="No se ha encontrado la palabra";
       
       if(aleman.containsKey(palabra)){
           
            resultado.setText(traduccion);
            
          
       }else{
           JOptionPane.showMessageDialog(null, "No existe la palabra");
       }
    }//GEN-LAST:event_buttonAlEspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton buttonAlEsp;
    private javax.swing.JButton buttonEspAl;
    private javax.swing.JButton buttonEspFr;
    private javax.swing.JButton buttonEspIn;
    private javax.swing.JButton buttonFrEsp;
    private javax.swing.JButton buttonInEsp;
    private javax.swing.JTextField campoPalabra;
    private javax.swing.JTextField campoTraduccion;
    private javax.swing.JLabel ingresaPalabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
